# Site settings
title: "Girish Jayappa"
# description: "My resume created in Jekyll"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Girish Jayappa"
resume_title:                   "JavaEE Developer"
resume_contact_email:           "girishj.86@gmail.com"
resume_header_contact_info:     ""
resume_header_intro:            "<p>Over 8+ years of experience in Java Full stack Development with major focus on backend with strong frontend development experience. 12+ years of overall experience in IT Industry. Extensively experienced in Requirements Gathering, Analysis, Design, Development, Implementation and Testing of Object Oriented and Web based highly scalable Enterprise Applications using Java/J2EE. Working experience with organizations like <strong>RSA Security, Oracle Corporation, SAP Labs, GE Global Research, Wipro Technologies </strong></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_medium_url:            "https://medium.com/@andrey.dobra"
  resume_linkedin_url:          "https://www.linkedin.com/in/girishj86/"
  resume_github_url:            "https://github.com/girishj86/"
  # resume_twitter_url:           "https://twitter.com/AndreyDbr"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
resume_website_url:           "http://www.letsprepareforinterview.com"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
